apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.50-192.168.1.59

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: devops-cluster
  namespace: metallb-system
