apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dmancloud/gitops-devops-cluster.git
    targetRevision: HEAD
    path: manifests/nexus
  destination: 
    server: https://kubernetes.default.svc
    namespace: nexus

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
