apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-system
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.13.7
    helm:
      releaseName: metallb
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - .spec.conversion.webhook.clientConfig.caBundle
    - .spec.conversion.webhook.clientConfig.service.name
    - .spec.conversion.webhook.clientConfig.service.namespace
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
